### ISSUE TITLE
Encrypted phone: "unable to find crypto footer"

### ISSUE THREAD

**Issue by mensoif** [TeamWin/android_device_lge_d855#3] opened 2015-12-04 20:34 UTC
When trying to use TWRP 2.8.7.0 with an encrypted LG G3 Europe (d855) I get : 
E: Could not mount /data and unable to find crypto footer.

**Comment by sfeh922** [comment] 2016-02-13 09:19
Still no decryption for /data in 3.0.0.0. Would it be possible to fix this? I came across that problem on the Nexus 4 on earlier versions, but it always got fixed quite fast. Thx.

**Comment by lambdaupb** [comment] 2016-07-16 10:38
I'm still seeing the same behaviour. Current CM13 nightly with official 3.0.2.0.

It seems there is development going on somewhere, but I cant find the source for it.
http://forum.xda-developers.com/lg-g3/development/recovery-twrp-3-0-0-0-t3309475

I tried that version, it at least asks for a password, but does not accept the correct one.

**Comment by TwizzyDizzy** [comment] 2016-11-24 21:26
Same situation here, no decryption of /data done on entering TWRP. 

Has anyone tested the version above? Can I help to test anything?

Cheers
Thomas

**Comment by lambdaupb** [comment] 2016-12-23 18:04
@TwizzyDizzy I'm using my own patched version since July and it works reliably for me.
https://github.com/lambdaupb/android_device_lge_d855/releases

**Comment by rotanid** [comment] 2016-12-23 21:55
woah, thank you very much @lambdaupb , i wish you would have written it earlier ;-)

**Comment by ZjemCiKolege** [comment] 2017-03-15 13:09
Fixed in next build this case can be closed :}

**Comment by lambdaupb** [comment] 2017-03-15 14:19
Awesome!
How was this fixed ? - I'm not seeing related commits.

Is the stuff somewhere in a different repo?

**Comment by ZjemCiKolege** [comment] 2017-03-15 17:10
cm14.1 branch

**Comment by rotanid** [comment] 2017-03-20 21:09
looking forward to a release containing the fix!

**Comment by TwizzyDizzy** [comment] 2017-03-21 17:32
So just to be on the safe side (since I'm just installing a new phone): As I see it, the fix @DimitriMayakovsky was talking about is not incorporated in the 3.1.0-0 yet, right? So he is obviously talking about a forthcoming release :)

Also, there has been [another commit](https://github.com/TeamWin/android_device_lge_d855/commit/2d6f40e58d0b6a0ccfadecd67880b5200de75db8) concerning the decryption feature in the cm-14.1 branch just recently. 

Cheers
Thomas

**Comment by ZjemCiKolege** [comment] 2017-03-21 19:13
no yet..

**Comment by ZjemCiKolege** [comment] 2017-03-21 19:15
@TwizzyDizzy 
https://www.androidfilehost.com/?fid=817550096634753040 but test this i using this and any work good :]

**Comment by TwizzyDizzy** [comment] 2017-03-21 19:22
Ah, no worries, I can (and want to) wait for an official release.

Cheers
Thomas

**Comment by ZjemCiKolege** [comment] 2017-03-21 19:46
This same source like official :] no any differences

**Comment by TwizzyDizzy** [comment] 2017-03-23 16:50
I just flashed (the officially released) TWRP 3.1.0-1. I can confirm, that the decryption of /data now works flawlessly.

For me, this issue is resolved. Thanks a lot for fixing it :)

Cheers
Thomas

**Comment by rotanid** [comment] 2017-03-23 22:03
dito, issue is resolved!

**Closed as completed** 2017-03-23 23:30 UTC
